theme: jekyll-theme-time-machine
tittle: Sxkki Blog
description: Blog for more interesting things.
[Twitter: @_sxkki](https://twitter.com/_sxkki) [Github: Sxkki](https://github.com/sxkki) [Instagram: _miguedono](https://www.instagram.com/_miguedono/)
[Email: LMMR8393@icloud.com]
